"""Add seller column to users

Revision ID: 48e610cf4cba
Revises: cdb7979ba226
Create Date: 2025-08-09 08:29:18.062145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e610cf4cba'
down_revision: Union[str, Sequence[str], None] = 'cdb7979ba226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'deleted')
    # ### end Alembic commands ###
