"""create products and categories tables

Revision ID: a0efcdc9e81f
Revises: 
Create Date: 2025-08-20 16:30:21.988517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0efcdc9e81f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa

def upgrade() -> None:
    # ### Create categories table ###
    op.create_table(
        'categories',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, nullable=False, unique=True),
        # checkfirst=  # prevents error if table exists
    )

    # ### Add category_id column to products ###
    op.add_column('products', sa.Column('category_id', sa.Integer, nullable=True))

    # ### Add foreign key constraint ###
    op.create_foreign_key(
        'products_category_id_fkey',  # constraint name
        'products',  # source table
        'categories',  # target table
        ['category_id'],  # source column
        ['id'],  # target column
        ondelete="SET NULL"  # optional: handle deletions
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
